name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            jraviles/dump1090
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: false
      - name: Push
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: jraviles/dump1090:latest
      - name: Generate Artifact Attestation for Docker Hub
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: docker.io/jraviles/dump1090
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
